### ISSUE TITLE
bhaptics Designer Integration

### ISSUE THREAD

**Issue by andytwoods** [bhaptics/tact-js#1]
Hi, 
can you provide examples on how to run .tact files? There is v little documentation on how your hardware can be linked with JS.
Best, 
Andy.

**Comment by westside** [comment]
Hi, 
We'll update the js library and add the .tact file example soon.
Please keep track this issue.

**Comment by andytwoods** [comment]
Have you more info on the data I can send the bhaptics server? I could then contribute to this project.

**Comment by andytwoods** [comment]
I've ported over functionality from your python project to https://github.com/andytwoods/tact-js. Communicates with server, no errors. Currently 'voluntarily confined' at home, so will need to test it with hardware when back at work.

**Comment by westside** [comment]
Sorry for very late response, and thank you for your work!

**Comment by westside** [comment]
@andytwoods  I've updated codes and you can just start from tact-js@0.2.0

**Comment by andytwoods** [comment]
could you re-build your dist? Folder not there now. Thanks.

**Comment by westside** [comment]
For the FileLoader, you can use as below. 


```
    var loader = new FileLoader();
    loader.load(fileDirectory, function (text, name) {
        tactJs.registerFile(name, text);
    });

```
