### ISSUE TITLE
tactgloves integration with WebXR browser

### ISSUE THREAD

**Issue by addy1997** [bhaptics/tact-js#32]
Hi @westside, 

Thanks for your help previously. I successfully integrated the haptics glove using the [aframe](https://aframe.io/) library ☺️. Further, I am looking to integrate these gloves with the WebXR browser. Do you think it is possible?

Please could you let me know that?

**Comment by westside** [comment]
@addy1997 Hi, really sorry for the late response. 

Tact-js is designed to operate exclusively on the Windows platform at this point. While employing WebXR in conjunction with Windows-based Virtual Reality (VR) systems is feasible and should function properly, it's important to note that this setup lacks support for other operating systems. Users aiming to implement or utilize these technologies on platforms other than Windows may encounter compatibility issues, as current support is limited to Windows environments.

**Comment by addy1997** [comment]
Hi @westside ,

Thanks for your reply. My question was not about the Windows operating system, it's about integrating the tact-gloves with [WebXR](https://immersiveweb.dev/). Is it possible to integrate the gloves with the WebXR platform?

**Comment by UXVirtual** [comment]
@addy1997 from the looks of things this library uses WebSockets under the hood to communicate with bHaptics Player. You could use this directly from a standalone WebXR app running on the Meta Quest browser, but you'd need to modify the example code and/or library to communicate over the network to a PC running bHaptics Player which also has the bHaptics devices connected via Bluetooth.

Alternatively you could try rolling your own 2D Android app using the bHaptics SDK which can run as a service on the Quest and communicate with it via OSC or a WebSocket to control the bHaptics devices. If you don't have much experience writing Android apps, you may be able to get AI assistants like Google Gemini write a lot of the boilerplate for you if you pass in the bHaptics Android SDK documentation or [sample code](https://github.com/bhaptics/tact-android) and tell the assistant which SDK API functions you want exposed via WebSocket.
