### ISSUE TITLE
PathMode

### ISSUE THREAD

**Issue by Code4Dopamine** [bhaptics/tact-js#4]
Hi! I've tried the example below
https://elated-noyce-f0332a.netlify.com/ 

But it seems like I'm getting similar feedback between **"Dot Mode"** and "**Path Mode**"?
Or is it working as intended?

----------------------------
**Dot Mode:**
![image](https://user-images.githubusercontent.com/11954656/100224828-afef6600-2f60-11eb-82b0-2581f67f9940.png)
**Path Mode:**
![image](https://user-images.githubusercontent.com/11954656/100224420-263f9880-2f60-11eb-9d0d-c7978092e580.png)
![image](https://user-images.githubusercontent.com/11954656/100224554-5129ec80-2f60-11eb-9877-913941a0f9c1.png)

Thanks a lot in advance!

**Comment by westside** [comment]
Yes, it only depends how you want to turn on the motors. 
If you want to turn on the motor with its index, 'DotMode' will be the option.On the other hand, if you want to turn on the motor in some specific position on the devices, you can use 'PathMode'.
For more complicated patterns, you can use the bhaptics designer. https://designer.bhaptics.com/

**Comment by Code4Dopamine** [comment]
I see, thank you for the clarification!
(I thought this would generate a "_**left to right movement vibration**_" between the "_**Path Points**_".
Or is this functionally similar to **bHaptic Designer** already open-sourced somewhere in this github?)

**Comment by westside** [comment]
Ah naming of the mode might be confusing.
Thank you for the comment.
